root = "."
tmp_dir = "tmp"

[build]
  cmd = "make generate && make build"
  bin = "./main"
  full_bin = ""
  include_ext = ["go", "templ"]
  exclude_dir = ["assets", "dist", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_watch = ["./node_modules/"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  include_file = []
  kill_delay = "10"
  rerun = false
  delay = 1000

[screen]
  clear_on_rebuild = true
